function P_ee = autoGen_eePos(q1,q2,l1,l2)
%AUTOGEN_EEPOS
%    P_EE = AUTOGEN_EEPOS(Q1,Q2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Dec-2021 21:50:18

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
P_ee = [-l1.*t4-l2.*(t2.*t5+t3.*t4);l1.*t2+l2.*(t2.*t3-t4.*t5);0.0];
