function Jac_ee = autoGen_eeJac(q1,q2,l1,l2)
%AUTOGEN_EEJAC
%    JAC_EE = AUTOGEN_EEJAC(Q1,Q2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Dec-2021 21:50:18

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t10 = -t9;
t11 = t7+t8;
t12 = l2.*t11;
t13 = t6+t10;
t14 = l2.*t13;
t15 = -t12;
t16 = -t14;
Jac_ee = reshape([0.0,0.0,1.0,t16-l1.*t2,t15-l1.*t4,0.0,0.0,0.0,1.0,t16,t15,0.0],[6,2]);
