function dJac_ee = autoGen_eeJacDot(q1,q2,qd1,qd2,l1,l2)
%AUTOGEN_EEJACDOT
%    DJAC_EE = AUTOGEN_EEJACDOT(Q1,Q2,QD1,QD2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Dec-2021 21:50:18

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t10 = -t9;
t11 = t7+t8;
t12 = t6+t10;
t13 = l2.*qd2.*t11;
t14 = l2.*qd2.*t12;
t15 = -t14;
dJac_ee = reshape([0.0,0.0,0.0,t13+qd1.*(l1.*t4+l2.*t11),t15-qd1.*(l1.*t2+l2.*t12),0.0,0.0,0.0,0.0,t13+l2.*qd1.*t11,t15-l2.*qd1.*t12,0.0],[6,2]);
