function [MM,FF] = autoGen_dynMat(q1,q2,qd1,qd2,l1,c1,c2,m1,m2,I1z,I2z,g)
%AUTOGEN_DYNMAT
%    [MM,FF] = AUTOGEN_DYNMAT(Q1,Q2,QD1,QD2,L1,C1,C2,M1,M2,I1Z,I2Z,G)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Dec-2021 21:51:58

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = c1.^2;
t7 = c2.^2;
t8 = l1.*t2;
t9 = l1.*t4;
t10 = t2.*t3;
t11 = t2.*t5;
t12 = t3.*t4;
t13 = t4.*t5;
t14 = -t13;
t15 = t11+t12;
t16 = c2.*t15;
t17 = t10+t14;
t18 = qd1.*t16;
t19 = qd2.*t16;
t20 = c2.*t17;
t23 = t9+t16;
t21 = qd1.*t20;
t22 = qd2.*t20;
t24 = qd1.*t23;
t25 = t8+t20;
t27 = t18+t19;
t28 = t16.*t23.*2.0;
t26 = qd1.*t25;
t29 = t21+t22;
t30 = t19+t24;
t31 = t20.*t25.*2.0;
t32 = t22+t26;
t33 = t20.*t30.*2.0;
t36 = t28+t31;
t34 = -t33;
t35 = t16.*t32.*2.0;
t37 = (m2.*t36)./2.0;
t38 = I2z+t37;
MM = reshape([I1z+I2z+(m1.*(t2.^2.*t6.*2.0+t4.^2.*t6.*2.0))./2.0+(m2.*(t23.^2.*2.0+t25.^2.*2.0))./2.0,t38,t38,I2z+(m2.*(t7.*t15.^2.*2.0+t7.*t17.^2.*2.0))./2.0],[2,2]);
if nargout > 1
    FF = [m2.*qd2.*(t33-t35+t23.*t29.*2.0-t25.*t27.*2.0).*(-1.0./2.0)+g.*m2.*t23+c1.*g.*m1.*t4;m2.*(t27.*t32.*2.0-t29.*t30.*2.0).*(-1.0./2.0)-(m2.*qd2.*(t33-t35+t16.*t29.*2.0-t20.*t27.*2.0))./2.0+g.*m2.*t16];
end
