function [P_COM,ALM,AG] = autoGen_cmmMat(q1,q2,qd1,qd2,l1,c1,c2,m1,m2,I1z,I2z)
%AUTOGEN_CMMMAT
%    [P_COM,ALM,AG] = AUTOGEN_CMMMAT(Q1,Q2,QD1,QD2,L1,C1,C2,M1,M2,I1Z,I2Z)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Dec-2021 22:17:02

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = I2z.*m1;
t7 = I2z.*m2;
t8 = m1+m2;
t9 = q1+q2;
t10 = c1.^2;
t11 = c2.^2;
t12 = l1.^2;
t13 = l1.*t2;
t14 = cos(t9);
t15 = l1.*t4;
t16 = sin(t9);
t17 = c1.*m1.*t2;
t18 = c1.*m1.*t4;
t21 = 1.0./t8;
P_COM = [-t21.*(t18+m2.*(t15+c2.*(t2.*t5+t3.*t4)));t21.*(t17+m2.*(t13+c2.*(t2.*t3-t4.*t5)));0.0];
if nargout > 1
    t22 = m1.*m2.*t11;
    t19 = c2.*t14;
    t20 = c2.*t16;
    t23 = t13+t19;
    t24 = t15+t20;
    ALM = [0.0;0.0;t21.*(qd1.*t6+qd1.*t7+qd2.*t6+qd2.*t7+qd1.*t22+qd2.*t22+I1z.*m1.*qd1+I1z.*m2.*qd1+m1.*m2.*qd1.*t10+m1.*m2.*qd1.*t12-c1.*l1.*m1.*m2.*qd1.*2.0-c1.*c2.*m1.*m2.*qd1.*t3.*2.0-c1.*c2.*m1.*m2.*qd2.*t3+c2.*l1.*m1.*m2.*qd1.*t3.*2.0+c2.*l1.*m1.*m2.*qd2.*t3);-qd1.*t17-m2.*(qd2.*t19+qd1.*t23);-qd1.*t18-m2.*(qd2.*t20+qd1.*t24);0.0];
end
if nargout > 2
    AG = reshape([0.0,0.0,t21.*(t6+t7+t22+I1z.*m1+I1z.*m2+m1.*m2.*t10+m1.*m2.*t12-c1.*l1.*m1.*m2.*2.0-c1.*c2.*m1.*m2.*t3.*2.0+c2.*l1.*m1.*m2.*t3.*2.0),-t17-m2.*t23,-t18-m2.*t24,0.0,0.0,0.0,t21.*(t6+t7+t22-c1.*c2.*m1.*m2.*t3+c2.*l1.*m1.*m2.*t3),-m2.*t19,-m2.*t20,0.0],[6,2]);
end
