function V_ee = autoGen_eeVel(q1,q2,qd1,qd2,l1,l2)
%AUTOGEN_EEVEL
%    V_EE = AUTOGEN_EEVEL(Q1,Q2,QD1,QD2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Dec-2021 21:50:18

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
V_ee = [0.0;0.0;qd1+qd2;-qd1.*(l2.*t3+l1.*cos(q1))-l2.*qd2.*t3;-qd1.*(l2.*t4+l1.*sin(q1))-l2.*qd2.*t4;0.0];
